CREATE TABLE `robotData` (
  `matchNum` text,
  `teamNum` int(11) DEFAULT '0',
  `allianceColor` text,
  `autonHighGoal` int(11) DEFAULT '0',
  `autonLowGoal` int(11) DEFAULT '0',
  `robotType` text,
  `robotSpeed` text,
  `intakeSpeed` text,
  `shootingSpeed` text,
  `teleopHighGoal` int(11) DEFAULT '0',
  `teleopLowGoal` int(11) DEFAULT '0',
  `scoresFromMultLoc` tinyint(4) DEFAULT '0',
  `towerCaptured` tinyint(4) DEFAULT '0',
  `goesUpRamp` tinyint(4) DEFAULT '0',
  `climbs` tinyint(4) DEFAULT '0',
  `climbsFailed` tinyint(4) DEFAULT '0',
  `climbsPoorly` tinyint(4) DEFAULT '0',
  `broken` tinyint(4) DEFAULT '0',
  `noShow` tinyint(4) DEFAULT '0',
  `chevalSelected` tinyint(4) DEFAULT '0',
  `drawbridgeSelected` tinyint(4) DEFAULT '0',
  `rockWallSelected` tinyint(4) DEFAULT '0',
  `moatSelected` tinyint(4) DEFAULT '0',
  `portcullisSelected` tinyint(4) DEFAULT '0',
  `sallyPortSelected` tinyint(4) DEFAULT '0',
  `rampartSelected` tinyint(4) DEFAULT '0',
  `roughTerrainSelected` tinyint(4) DEFAULT '0',
  `autonCheval` tinyint(4) DEFAULT '0',
  `chevalAutoPoor` tinyint(4) DEFAULT '0',
  `chevalAutoFail` tinyint(4) DEFAULT '0',
  `autonDrawbridge` tinyint(4) DEFAULT '0',
  `drawbridgeAutoPoor` tinyint(4) DEFAULT '0',
  `drawbridgeAutoFail` tinyint(4) DEFAULT '0',
  `autonRockWall` tinyint(4) DEFAULT '0',
  `rockWallAutoPoor` tinyint(4) DEFAULT '0',
  `rockWallAutoFail` tinyint(4) DEFAULT '0',
  `autonMoat` tinyint(4) DEFAULT '0',
  `moatAutoPoor` tinyint(4) DEFAULT '0',
  `moatAutoFail` tinyint(4) DEFAULT '0',
  `autonPortcullis` tinyint(4) DEFAULT '0',
  `portcullisAutoPoor` tinyint(4) DEFAULT '0',
  `portcullisAutoFail` tinyint(4) DEFAULT '0',
  `autonSallyPort` tinyint(4) DEFAULT '0',
  `sallyPortAutoPoor` tinyint(4) DEFAULT '0',
  `sallyPortAutoFail` tinyint(4) DEFAULT '0',
  `autonRampart` tinyint(4) DEFAULT '0',
  `rampartAutoPoor` tinyint(4) DEFAULT '0',
  `rampartAutoFail` tinyint(4) DEFAULT '0',
  `autonRoughTerrain` tinyint(4) DEFAULT '0',
  `roughTerrainAutoPoor` tinyint(4) DEFAULT '0',
  `roughTerrainAutoFail` tinyint(4) DEFAULT '0',
  `autonLowBar` tinyint(4) DEFAULT '0',
  `lowBarAutoPoor` tinyint(4) DEFAULT '0',
  `lowBarAutoFail` tinyint(4) DEFAULT '0',
  `teleopCheval` tinyint(4) DEFAULT '0',
  `chevalTelePoor` tinyint(4) DEFAULT '0',
  `chevalTeleFail` tinyint(4) DEFAULT '0',
  `teleopDrawbridge` tinyint(4) DEFAULT '0',
  `drawbridgeTelePoor` tinyint(4) DEFAULT '0',
  `drawbridgeTeleFail` tinyint(4) DEFAULT '0',
  `teleopRockWall` tinyint(4) DEFAULT '0',
  `rockWallTelePoor` tinyint(4) DEFAULT '0',
  `rockWallTeleFail` tinyint(4) DEFAULT '0',
  `teleopMoat` tinyint(4) DEFAULT '0',
  `moatTelePoor` tinyint(4) DEFAULT '0',
  `moatTeleFail` tinyint(4) DEFAULT '0',
  `teleopPortcullis` tinyint(4) DEFAULT '0',
  `portcullisTelePoor` tinyint(4) DEFAULT '0',
  `portcullisTeleFail` tinyint(4) DEFAULT '0',
  `teleopSallyPort` tinyint(4) DEFAULT '0',
  `sallyPortTelePoor` tinyint(4) DEFAULT '0',
  `sallyPortTeleFail` tinyint(4) DEFAULT '0',
  `teleopRampart` tinyint(4) DEFAULT '0',
  `rampartTelePoor` tinyint(4) DEFAULT '0',
  `rampartTeleFail` tinyint(4) DEFAULT '0',
  `teleopRoughTerrain` tinyint(4) DEFAULT '0',
  `roughTerrainTelePoor` tinyint(4) DEFAULT '0',
  `roughTerrainTeleFail` tinyint(4) DEFAULT '0',
  `teleopLowBar` tinyint(4) DEFAULT '0',
  `lowBarTelePoor` tinyint(4) DEFAULT '0',
  `lowBarTeleFail` tinyint(4) DEFAULT '0',
  `yellowCard` tinyint(4) DEFAULT '0',
  `redCard` tinyint(4) DEFAULT '0',
  `numTechFouls` int(11) DEFAULT '0',
  `comments` text,
  `name` text,
  `team_score` int(11) DEFAULT NULL,
  `eventCode` text,
  `uuid` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8